-- https://school.programmers.co.kr/learn/courses/30/lessons/299310

SELECT A.YEAR,A.YEAR_MAX - B.SIZE_OF_COLONY AS YEAR_DEV,B.ID
FROM(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM ECOLI_DATA
    GROUP BY 1
) AS A,ECOLI_DATA AS B 
WHERE A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY 1,2